In [1]:
#1
import numpy as np
arr = np.arange(0, 10, 1)

In [3]:
#2
arr = np . ones ((3 ,3) ) > 0
print(arr)
arr1 = np . ones ((3 ,3) , dtype = bool )
print(arr1)
arr2 = np . full ((3 ,3) , fill_value = True , dtype = bool )
print(arr2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
#3
import numpy as np
arr = np.arange(0, 10)
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [5]:
#4
import numpy as np
arr = np.arange(0, 10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [6]:
#5
import numpy as np
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
#6
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print(" Result : \n ", c)

 Result : 
  [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [8]:
#7
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
print(" C = ", c)

 C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [9]:
#8
import numpy as np
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [10]:
#9
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
print(" result ", a[index])

 result  [ 6  9 10]


In [11]:
#10
import numpy as np

def maxx(x, y):
  if x >= y:
    return x
  else:
    return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


In [12]:
#11
import numpy as np
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print(" Result ", np.where(a < b, b, a))

 Result  [6 7 9 8 9 7 5]


In [13]:
#12
# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = np.uint8((np.max(img, axis=2) + np.min(img, axis=2)) / 2)

gray_img_01[0, 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 51.0MB/s]


102

In [14]:
#13
# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg.imread('/content/dog.jpeg')
gray_img_02 = np.uint8(np.mean(img, axis=2))

gray_img_02[0, 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 42.9MB/s]


107

In [18]:
#14
# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg.imread('/content/dog.jpeg')
gray_img_03 = np.uint8(0.21 * img[:, :, 0] + 0.72 * img[:, :, 1] + 0.07 * img[:, :, 2])

gray_img_03[0, 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 34.9MB/s]


126

In [15]:
#15
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()
print(f"Max: {data[:, 3].max()} - Index: {np.argmax(data[:, 3])}")

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 11.8MB/s]
Max: 27.0 - Index: 175


In [19]:
#16
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()
print(f"Giá trị trung bình của cột TV là: {data[:, 0].mean()}")

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 13.4MB/s]
Giá trị trung bình của cột TV là: 147.0425


In [17]:
#17
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()
print(f"Số lượng bản ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20 là: {np.sum(data[:, 3] >= 20)}")

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 14.4MB/s]
Số lượng bản ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20 là: 40


In [20]:
#18
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()
print(f"Giá trị trung bình của cột Radio thoả mãn điều kiện giá trị tương ứng trên cột Sales lớn hơn hoặc bằng 15 là: {data[data[:, 3] >= 15, 1].mean()}")

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 7.23MB/s]
Giá trị trung bình của cột Radio thoả mãn điều kiện giá trị tương ứng trên cột Sales lớn hơn hoặc bằng 15 là: 26.22293577981651


In [21]:
#19
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()
print(f"Tổng các hàng của cột Sales với điều kiện giá trị Newspaper lớn hơn giá trị trung bình của cột Newspaper là: {data[data[:, 2] > data[:, 2].mean(), 3].sum()}")

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 12.9MB/s]
Tổng các hàng của cột Sales với điều kiện giá trị Newspaper lớn hơn giá trị trung bình của cột Newspaper là: 1405.1


In [24]:
#20
# Download data

!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
import numpy as np
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()
A = data[:, 3].mean()  # Tính giá trị trung bình của cột Sales
scores = np.where(data[:, 3] > A, 'Good', np.where(data[:, 3] < A, 'Bad', 'Average'))
print(scores[7:10])

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 14.1MB/s]
['Bad' 'Bad' 'Good']


In [25]:
#21
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
import numpy as np
df = pd.read_csv('/content/advertising.csv')

data = df.to_numpy()
B = data[:, 3][np.argmin(np.abs(data[:, 3] - data[:, 3].mean()))]  # Tìm giá trị gần nhất với giá trị trung bình
scores = np.where(data[:, 3] > B, 'Good', np.where(data[:, 3] < B, 'Bad', 'Average'))
print(scores[7:10])

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 15.0MB/s]
['Bad' 'Bad' 'Good']
