In [2]:
class CustomLinearRegression:
    def __init__(self, X_data, y_target, learning_rate=0.01, num_epochs=10000):
        self.num_samples = X_data.shape[0]
        self.X_data = np.c_[np.ones((self.num_samples, 1)), X_data]
        self.y_target = y_target
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs

        # Initial weights
        self.theta = np.random.randn(self.X_data.shape[1], 1)
        self.losses = []

    def compute_loss(self, y_pred, y_target):
        errors = y_pred - y_target
        loss = (1 / (2 * len(y_target))) * np.sum(errors ** 2)
        return loss

    def predict(self, X_data):
        X_data = np.c_[np.ones((X_data.shape[0], 1)), X_data]
        y_pred = np.dot(X_data, self.theta)
        return y_pred

    def fit(self):
        for epoch in range(self.num_epochs):
            # Predict
            y_pred = self.predict(self.X_data)

            # Compute the loss
            loss = self.compute_loss(y_pred, self.y_target)
            self.losses.append(loss)

            # Compute the gradient
            loss_grd = 2 * (y_pred - self.y_target) / self.num_samples
            gradients = np.dot(self.X_data.T, loss_grd)

            # Update the weights
            self.theta -= self.learning_rate * gradients

            if epoch % 50 == 0:
                print(f'Epoch: {epoch} - Loss: {loss}')

        return {
            'loss': sum(self.losses) / len(self.losses),
            'weight': self.theta
        }

In [3]:
def r2score ( y_pred , y ):
  rss = np . sum (( y_pred - y ) ** 2)
  tss = np . sum (( y - y . mean () ) )
  r2 = 1 - ( rss / tss )
  return r2

In [4]:
import numpy as np
from sklearn.metrics import r2_score

# Case 1
y_pred1 = np.array([1, 2, 3, 4, 5])
y1 = np.array([1, 2, 3, 4, 5])
r2_case1 = r2_score(y1, y_pred1)

# Case 2
y_pred2 = np.array([1, 2, 3, 4, 5])
y2 = np.array([3, 5, 5, 2, 4])
r2_case2 = r2_score(y2, y_pred2)

print(f"Case 1 R2 Score: {r2_case1}")
print(f"Case 2 R2 Score: {r2_case2}")

Case 1 R2 Score: 1.0
Case 2 R2 Score: -2.235294117647059


In [5]:
import numpy as np

def create_polynomial_features(X, degree=2):
    """Creates polynomial features.

    Args:
        X : A numpy array for the data.
        degree : An integer for the degree of the generated polynomial function.
    """
    X_new = X
    for d in range(2, degree + 1):
        X_new = np.concatenate((X_new, X**d), axis=1)
    return X_new

# Example usage
X = np.array([[1], [2], [3]])
X_poly = create_polynomial_features(X, degree=2)
print(X_poly)

[[1 1]
 [2 4]
 [3 9]]


In [7]:
import numpy as np

def create_polynomial_features(X, degree=2):
    """Creates the polynomial features.

    Args:
        X : A numpy array for the data.
        degree : An integer for the degree of the generated polynomial function.
    """
    X_mem = []
    for X_sub in X.T:
        X_new = X_sub
        for d in range(2, degree + 1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T

# Example usage
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])
X_poly = create_polynomial_features(X, degree=2)
print(X_poly)

[[ 1  1  2  4]
 [ 2  4  3  9]
 [ 3  9  4 16]]


sales prediction

In [16]:
import pandas as pd
dataset_path = '/content/SalesPrediction.csv'

df = pd. read_csv (dataset_path)
df.head()
df= pd.get_dummies(df)

In [17]:
# Handle Null values
df = df.fillna(df.mean())

# Get features
X = df[['TV', 'Radio', 'Social Media', 'Influencer_Macro',
        'Influencer_Mega', 'Influencer_Micro', 'Influencer_Nano']]
y = df[['Sales']]

# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.33,
    random_state=0
)

In [23]:
from sklearn . preprocessing import StandardScaler
scaler = StandardScaler ()
X_train_processed = scaler . fit_transform ( X_train)
X_test_processed = scaler.transform(X_test)
scaler . mean_[0]

54.173577723283785

In [24]:
from sklearn . preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures ( degree =2)
X_train_poly = poly_features . fit_transform ( X_train_processed )
X_test_poly = poly_features . transform (X_test_processed)

In [25]:
from sklearn . linear_model import LinearRegression
from sklearn . metrics import r2_score
poly_model = LinearRegression ()
poly_model . fit ( X_train_poly , y_train )
preds = poly_model . predict ( X_test_poly )
r2_score ( y_test , preds )

0.9951796158547627